!/bin/bash
##################################
: '
Salmon quantification in mapping-based
mode using the index generated by index.sh.

For paired-end reads.

Just like qualc.sh, user can optionally
specify a path for external reads if 
reads are not already stored in the fastq/
file.

The quantification is also timed as it can be a long process

[October 18, 2024]:
- Added seqBias and posBias flags to quantification
'
##################################
cd ./index
INDEX_PATH=$PWD
printf "Index path $INDEX_PATH created\n"
cd .. 
echo $PWD

cd ./fastq
mkdir -p quants
cd quants
QUANTS_PATH=$PWD
printf "Quantifications path $QUANTS_PATH created\n"
cd ..
cd .. 
echo $PWD


# The READS_PATH here is for reading .fastq files (gzipped or otherwise from
# a given directory, but if that directory is not specified, then the fastq/
# subdirectory is used by default (assuming it exists)
READS_PATH=${1:-./fastq} 
cd "$READS_PATH"
for fn in *_R1_001.fastq.gz; do # Make sure quantification runs once for each pair
  printf "Filename: $fn\n" # test
  base=$(echo "$fn" | sed 's/_R1_001.fastq.gz//') 
  printf "Base: ${base}\n" # test
  printf "Left: ${base}_R1_001.fastq.gz\n"
  printf "Right: ${base}_R2_001.fastq.gz\n\n"
  salmon quant -i "$INDEX_PATH" -l A -1 "${base}_R1_001.fastq.gz" -2 "${base}_R2_001.fastq.gz" -p 12 --validateMappings -o "${QUANTS_PATH}/${base}_quant" --seqBias --posBias
done
